### ISSUE TITLE
Unable to create F_SERIAL function for gadget

### ISSUE THREAD

**Issue by TheSharma** [libusbg/libusbg#16]
Hello,

F_SERIAL function creation is returning with "USBG_ERROR_NO_MEM" "allocating function" , from usbg_create_function. Below patch solves the issue when I try to create F_SERIAL:

--- src/usbg.c  2014-09-23 21:59:41.000000000 +0530
+++ /home/diwakar/libusbg-0.1.0/src/usbg.c  2015-05-26 14:42:39.000000000 +0530
@@ -319,7 +319,7 @@

 const const char *usbg_get_function_type_str(usbg_function_type type)
 {
-   return type > 0 && type < sizeof(function_names)/sizeof(char *) ?
-   return type >= 0 && type < sizeof(function_names)/sizeof(char *) ?
          function_names[type] : NULL;
  }

**Comment by kopasiak** [comment]
This bug has been fixed very long time ago. Please see commit:
https://github.com/kopasiak/libusbg/commit/d159c87d9355bce26df676a43ae36c951102e8ff

As you see libusbg repository is a little bit stale so together with a few community members we try to continue development here: 

https://github.com/kopasiak/libusbg

Cheers

**Comment by TheSharma** [comment]
Cheers.. cloned https://github.com/kopasiak/libusbg
